# This is the First Workflow for Testing with Github Actions

name: Pod Lint
on:
  workflow_dispatch:
env:
  ENCODING: LC_CTYPE=en_US.UTF-8
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
jobs:
  pod-lint:
    runs-on: macos-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Linting PodSpec for Cocoapods"
        run: export "${{ env. ENCODING }}" | pod lib lint
        shell: bash